site_name: fiware-cosmos
site_url: https://fiware-cosmos.readthedocs.org
repo_url: https://github.com/telefonicaid/fiware-cosmos.git
site_description: Cosmos Documentation
docs_dir: doc/manuals
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_processing.css"]
google_analytics: ['UA-84812269-1', 'fiware-cosmos.readthedocs.io']
pages:
  - Home: index.md
  - 'Quick Start Guide': 'quick_start_guide_new.md'
  - 'Installation and Administration manual':
      - 'Introduction': 'installation_and_administration_manual/introduction.md'
      - 'Some words about Cosmos and its ecosystem': 'installation_and_administration_manual/some_words_about_cosmos_and_ecosystem.md'
      - 'HAAS engine (Sahara version)': 'installation_and_administration_manual/haas_engine_sahara.md'
      - 'HAAS engine (shared Hadoop version)': 'installation_and_administration_manual/haas_engine_shared_hadoop.md'
      - 'Storage cluster': 'installation_and_administration_manual/storage_cluster.md'
      - 'GUI': 'installation_and_administration_manual/gui.md'
      - 'Tidoop': 'installation_and_administration_manual/tidoop.md'
      - 'Auth server': 'installation_and_administration_manual/auth_server.md'
      - 'OAuth2 proxy': 'installation_and_administration_manual/oauth2_proxy.md'
      - 'OAuth2 Hive authentication provider': 'installation_and_administration_manual/oauth2_hive_auth_provider.md'
      - 'Cygnus': 'installation_and_administration_manual/cygnus.md'
      - 'Sanity Check Procedures': 'installation_and_administration_manual/sanity_check_procedures.md'
      - 'Diagnosis Procedures': 'installation_and_administration_manual/diagnosis_procedures.md'
  - 'User and Programmer manual':
      - 'Introduction': 'user_and_programmer_manual/introduction.md'
      - 'Using the GUI': 'user_and_programmer_manual/using_gui.md'
      - 'OAuth2 in Cosmos APIs': 'user_and_programmer_manual/using_oauth2.md'
      - 'Data management and I/O': 'user_and_programmer_manual/data_management_and_io.md'
      - 'Requesting computing resources': 'user_and_programmer_manual/request_computing_resources.md'
      - 'Using Tidoop': 'user_and_programmer_manual/using_tidoop.md'
      - 'Using Hadoop and its ecosystem': 'user_and_programmer_manual/using_hadoop_and_ecosystem.md'
